/**
 * Imperium Roma — static site build pipeline.
 *
 * Turns the hand-maintained source pages into an optimized `dist/`:
 *   1. Resolves `<!-- @include partials/x.html -->` directives (single source of truth
 *      for header/footer/etc).
 *   2. Localises pages: resolves `{{t:key}}`-style placeholders from `i18n/<locale>.json`,
 *      expands `<!-- @hreflang -->` into the alternate-language links for the page, and
 *      injects the runtime strings the shared scripts read (`window.I18N`).
 *   3. Minifies CSS (lightningcss) and JS (esbuild) and HTML (html-minifier-terser).
 *   4. Content-hashes classic CSS/JS filenames for cache-busting and rewrites references.
 *   5. Generates `sitemap.xml` from the pages actually built, with per-language alternates.
 *
 * Languages
 * ---------
 * English is the default locale and lives at the site root, exactly as before. Every
 * other locale is a top-level folder named by its language code (`uk/about/index.html`
 * -> `/uk/about/`) and needs a dictionary at `i18n/<code>.json`. A page exists in a
 * language only if its file exists; nothing is auto-translated. See docs/DEVELOPMENT.md.
 *
 * ES-module JS (files using import/export, or loaded with <script type="module">) is
 * minified *in place* and never renamed, so its relative `import` specifiers keep working.
 *
 * Usage:
 *   node build.mjs           production build  -> dist/
 *   node build.mjs --dev     fast build (no minify, no hashing) used by the dev server
 */
import {
  readFileSync, writeFileSync, mkdirSync, rmSync, cpSync,
  statSync, readdirSync, existsSync,
} from 'node:fs';
import { join, relative, dirname, extname, resolve, sep } from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { transform as esbuildTransform } from 'esbuild';
import { transform as lightningTransform } from 'lightningcss';
import { minify as minifyHtml } from 'html-minifier-terser';

const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = join(ROOT, 'dist');

/* ------------------------------------------------------------------ config */

const SITE_ORIGIN = 'https://imperiumroma.com';

// The locale served from the site root (no URL prefix). Its dictionary is also the
// fallback for any key another locale has not translated yet.
const DEFAULT_LOCALE = 'en';
const I18N_DIR = join(ROOT, 'i18n');

// Directories never copied into dist (build-time only or repo-only).
const EXCLUDE_DIRS = new Set([
  'dist', 'node_modules', '.git', '.github', '.vscode', 'logs',
  'partials', 'scripts', 'docs', 'i18n',
  // Composer dependencies for the PHP endpoints. CI uploads vendor/ in its own
  // step: it must be copied byte-for-byte, never minified or scanned for pages.
  'vendor',
]);

// Individual files never copied into dist.
// sitemap.xml is generated by this build; a stray source copy must never shadow it.
const EXCLUDE_FILES = new Set([
  'build.mjs', 'dev.mjs', 'package.json', 'package-lock.json', 'composer.json', 'composer.lock',
  'compare-results.json', // scripts/compare-coin-models.php output
  'pnpm-lock.yaml', 'yarn.lock', '.gitignore', 'README.md',
  'DEPLOYMENT.md', 'Imperium.png', 'deploy.ps1', '.DS_Store', 'sitemap.xml',
  // Real credentials (gitignored, uploaded to the server by hand). Never copy
  // them into dist/: the dev server serves dist/ to the whole local network
  // without running PHP, so a key in dist/config/ would be readable as text.
  'anthropic.php', 'telegram.php', 'newsletter.php',
]);

// The root .htaccess (HTTPS redirect, security headers, caching, compression,
// sensitive-file protection) now ships with every build. Flip to `true` if IONOS
// ever needs a different .htaccess to be authoritative instead.
const EXCLUDE_ROOT_HTACCESS = false;

// Conservative HTML minification: only strips whitespace and comments. Never rewrites
// attributes or inline JS/CSS, so behaviour and JSON-LD are byte-safe.
const HTML_MIN_OPTS = {
  collapseWhitespace: true,
  conservativeCollapse: true,
  removeComments: true,
  ignoreCustomComments: [/^!/],
  keepClosingSlash: true,
  caseSensitive: true,
  minifyJS: false,
  minifyCSS: false,
  removeAttributeQuotes: false,
  html5: true,
  // App pages embed HTML inside JS template literals; best-effort instead of throwing.
  continueOnParseError: true,
};

const JS_TARGET = 'es2019';

/* ----------------------------------------------------------------- helpers */

let DEV = false;

const toWebPath = (abs) => '/' + relative(ROOT, abs).split(sep).join('/');

const fromWebPath = (webPath) => {
  const clean = webPath.replace(/[?#].*$/, '').replace(/\/{2,}/g, '/');
  return join(ROOT, clean.replace(/^\//, ''));
};

const hash8 = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, 8);

const hashedWebPath = (webPath, content) => {
  const ext = extname(webPath);
  return `${webPath.slice(0, -ext.length)}.${hash8(content)}${ext}`;
};

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const escapeXml = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function writeDist(webPath, content) {
  const abs = join(DIST, webPath.replace(/^\//, ''));
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}

function walk(dir, acc) {
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name);
    const rel = relative(ROOT, abs);
    if (statSync(abs).isDirectory()) {
      if (!EXCLUDE_DIRS.has(name)) walk(abs, acc);
      continue;
    }
    if (EXCLUDE_FILES.has(name)) continue;
    if (EXCLUDE_ROOT_HTACCESS && rel === '.htaccess') continue;
    const ext = extname(name).toLowerCase();
    if (ext === '.html') acc.html.push(abs);
    else if (ext === '.css') acc.css.push(abs);
    else if (ext === '.js') acc.js.push(abs);
    else acc.other.push(abs);
  }
}

/**
 * Build the set of JS files that must NOT be renamed: anything loaded as
 * `<script type="module">`, anything containing top-level import/export, and the
 * transitive closure of their local imports.
 */
function computeModuleSet(htmlFiles, jsFiles) {
  const set = new Set();

  for (const html of htmlFiles) {
    const src = readFileSync(html, 'utf8');
    for (const [tag] of src.matchAll(/<script\b[^>]*>/gi)) {
      if (!/type\s*=\s*["']module["']/i.test(tag)) continue;
      const m = tag.match(/src\s*=\s*["']([^"']+)["']/i);
      if (!m) continue;
      const p = fromWebPath(m[1]);
      if (existsSync(p)) set.add(p);
    }
  }

  for (const js of jsFiles) {
    const s = readFileSync(js, 'utf8');
    if (/(^|\n)\s*import[\s{('"*]/.test(s) || /(^|\n)\s*export[\s{ *]/.test(s)) set.add(js);
  }

  const queue = [...set];
  const addSpec = (spec, importer) => {
    if (!spec.startsWith('.') && !spec.startsWith('/')) return; // bare/remote
    const p = spec.startsWith('/')
      ? fromWebPath(spec)
      : resolve(dirname(importer), spec.replace(/[?#].*$/, ''));
    if (existsSync(p) && !set.has(p)) { set.add(p); queue.push(p); }
  };
  while (queue.length) {
    const f = queue.pop();
    const s = readFileSync(f, 'utf8');
    for (const m of s.matchAll(/\bimport\s+(?:[^'"]*?\sfrom\s+)?['"]([^'"]+)['"]/g)) addSpec(m[1], f);
    for (const m of s.matchAll(/\bexport\s+[^'"]*?\sfrom\s+['"]([^'"]+)['"]/g)) addSpec(m[1], f);
  }
  return set;
}

function resolveIncludes(html, fromFile, depth = 0) {
  if (depth > 10) throw new Error(`include depth exceeded in ${fromFile}`);
  return html.replace(
    /^[ \t]*<!--\s*@include\s+([^\s>]+)\s*-->[ \t]*\r?$/gm,
    (_m, incPath) => {
      const p = fromWebPath(incPath);
      if (!existsSync(p)) throw new Error(`include not found: "${incPath}" (in ${fromFile})`);
      return resolveIncludes(readFileSync(p, 'utf8'), p, depth + 1);
    },
  );
}

/* ------------------------------------------------------------------- i18n */

/** `i18n/*.json` -> { en: {...}, uk: {...} }. The default locale is required. */
function loadLocales() {
  const locales = {};
  if (existsSync(I18N_DIR)) {
    for (const name of readdirSync(I18N_DIR)) {
      if (!name.endsWith('.json')) continue;
      const code = name.slice(0, -'.json'.length);
      locales[code] = JSON.parse(readFileSync(join(I18N_DIR, name), 'utf8'));
    }
  }
  if (!locales[DEFAULT_LOCALE]) {
    throw new Error(`i18n/${DEFAULT_LOCALE}.json is required (default locale dictionary)`);
  }
  return locales;
}

/** Default locale first, then the rest alphabetically — the order the switcher shows. */
const localeOrder = (locales) =>
  [DEFAULT_LOCALE, ...Object.keys(locales).filter((l) => l !== DEFAULT_LOCALE).sort()];

/**
 * Which language a source page is in, and its locale-agnostic identity.
 *   about/index.html     -> { locale: 'en', canon: '/about/' }
 *   uk/about/index.html  -> { locale: 'uk', canon: '/about/' }
 *   uk/404.html          -> { locale: 'uk', canon: '/404.html' }
 * `canon` is what ties the translations of one page together (hreflang, switcher, sitemap).
 */
function pageIdentity(htmlAbs, locales) {
  const parts = relative(ROOT, htmlAbs).split(sep);
  let locale = DEFAULT_LOCALE;
  if (parts.length > 1 && parts[0] !== DEFAULT_LOCALE && locales[parts[0]]) locale = parts.shift();
  const canon = ('/' + parts.join('/')).replace(/(^|\/)index\.html$/, '$1');
  return { locale, canon };
}

/** Web path of a canonical page in a given locale: '/about/' + 'uk' -> '/uk/about/'. */
const localizedPath = (canon, locale) => (locale === DEFAULT_LOCALE ? canon : `/${locale}${canon}`);

function lookup(dict, dotted) {
  return dotted.split('.').reduce((o, k) => (o && typeof o === 'object' ? o[k] : undefined), dict);
}

/**
 * Resolve everything language-dependent in one page. Runs after includes, so
 * partials can use the same placeholders as pages:
 *
 *   {{t:footer.subscribe}}   dictionary string (falls back to the default locale)
 *   {{lang}}                 locale code, e.g. for <html lang="{{lang}}">
 *   {{prefix}}               '' for the default locale, '/uk' otherwise
 *   {{link:/about/#team}}    same path in this page's language if that page exists
 *                            in it, otherwise the default-locale path (never a 404)
 *   {{alt:uk}}               this page in locale `uk`, or that locale's home page
 *   {{langswitch}}           one <a> per locale, for the header language switcher
 *   {{langmeta:label}}       this page's locale label / native name from _meta
 *                            (also {{langmeta:name}}), for the switcher button
 *   <!-- @hreflang -->       <link rel="alternate" hreflang> block for this page
 */
function localizeHtml(html, page, ctx) {
  const { locale, canon } = page;
  const { locales, order, pageIndex, file } = ctx;
  const dict = locales[locale];
  const fallback = locales[DEFAULT_LOCALE];
  const available = pageIndex.get(canon) || new Set();
  const prefix = locale === DEFAULT_LOCALE ? '' : `/${locale}`;

  const altPath = (l) => (available.has(l) ? localizedPath(canon, l) : localizedPath('/', l));

  const t = (key) => {
    let v = lookup(dict, key);
    if (v === undefined) {
      v = lookup(fallback, key);
      if (v === undefined) throw new Error(`i18n: missing key "${key}" (in ${file})`);
      if (locale !== DEFAULT_LOCALE) console.warn(`  ! i18n: "${key}" not translated for "${locale}" (${file})`);
    }
    return String(v);
  };

  const link = (target) => {
    const m = target.match(/^([^?#]*)(.*)$/);
    const [path, rest] = [m[1], m[2]];
    const set = pageIndex.get(path);
    return (set && set.has(locale) ? localizedPath(path, locale) : path) + rest;
  };

  const langswitch = () => order.map((l) => {
    const meta = locales[l]._meta || {};
    const label = meta.label || l.toUpperCase();
    const name = meta.name || l;
    const current = l === locale ? ' aria-current="page"' : '';
    return `<a href="${altPath(l)}" hreflang="${l}" lang="${l}" data-lang="${l}"${current}>`
      + `<span class="lang-menu__name">${name}</span><span class="lang-menu__code" aria-hidden="true">${label}</span></a>`;
  }).join('');

  const langmeta = (key) => {
    const meta = dict._meta || {};
    if (key === 'label') return meta.label || locale.toUpperCase();
    if (key === 'name') return meta.name || locale;
    throw new Error(`i18n: unknown {{langmeta:${key}}} (in ${file})`);
  };

  html = html.replace(/^[ \t]*<!--\s*@hreflang\s*-->[ \t]*\r?$/gm, () => {
    const lines = order
      .filter((l) => available.has(l))
      .map((l) => `<link rel="alternate" hreflang="${l}" href="${SITE_ORIGIN}${localizedPath(canon, l)}" />`);
    const xDefault = available.has(DEFAULT_LOCALE) ? DEFAULT_LOCALE : order.find((l) => available.has(l));
    lines.push(`<link rel="alternate" hreflang="x-default" href="${SITE_ORIGIN}${localizedPath(canon, xDefault)}" />`);
    return '    ' + lines.join('\n    ');
  });

  html = html.replace(
    /\{\{\s*(t|link|alt|lang|prefix|langswitch|langmeta)(?::([^}\s]+))?\s*\}\}/g,
    (_m, kind, arg) => {
      switch (kind) {
        case 't': return t(arg);
        case 'link': return link(arg);
        case 'alt': return altPath(arg);
        case 'lang': return locale;
        case 'prefix': return prefix;
        case 'langswitch': return langswitch();
        case 'langmeta': return langmeta(arg);
        default: return _m;
      }
    },
  );

  return html;
}

/**
 * Strings the shared scripts need at runtime (form/newsletter messages, carousel
 * labels…), plus what the language banner needs to offer another locale. Injected
 * into <head> so a single hashed script file serves every language.
 */
function runtimeI18nTag(page, ctx) {
  const { locales, order, pageIndex } = ctx;
  const available = pageIndex.get(page.canon) || new Set();
  const dict = locales[page.locale];
  const payload = {
    lang: page.locale,
    js: { ...(locales[DEFAULT_LOCALE].js || {}), ...(dict.js || {}) },
    alt: Object.fromEntries(order.map((l) => [
      l, available.has(l) ? localizedPath(page.canon, l) : localizedPath('/', l),
    ])),
    locales: Object.fromEntries(order.map((l) => {
      const meta = locales[l]._meta || {};
      return [l, { label: meta.label || l.toUpperCase(), name: meta.name || l, banner: meta.banner || null }];
    })),
  };
  // `<` can never appear raw inside a <script>, or "</script>" in a string would end it.
  const json = JSON.stringify(payload).replace(/</g, '\\u003c');
  return `<script>window.I18N=${json};</script>`;
}

/* ---------------------------------------------------------------- sitemap */

/** Pages that must never be listed: error page, the logged-in app, auth screens. */
const isSitemapExcluded = (canon) =>
  canon === '/404.html' || canon.startsWith('/domus/') || canon.startsWith('/login/');

function sitemapMeta(canon) {
  if (canon === '/') return { changefreq: 'weekly', priority: '1.0' };
  if (canon === '/services/' || canon === '/bibliotheca/') return { changefreq: 'weekly', priority: '0.9' };
  if (canon === '/about/' || canon === '/authenticity/') return { changefreq: 'monthly', priority: '0.8' };
  if (canon === '/contact/') return { changefreq: 'monthly', priority: '0.7' };
  if (canon.startsWith('/bibliotheca/')) return { changefreq: 'monthly', priority: '0.7' };
  if (canon.startsWith('/policies/')) return { changefreq: 'yearly', priority: '0.3' };
  return { changefreq: 'monthly', priority: '0.5' };
}

/**
 * Last commit date per tracked file, from a single `git log` pass. Needs the full
 * history (the deploy workflow checks out with fetch-depth: 0); on a shallow clone
 * or outside git, files fall back to their mtime. Skipped in dev builds: a stable
 * lastmod only matters for what crawlers see, and the pass costs a git spawn per rebuild.
 */
function gitLastModified() {
  const map = new Map();
  if (DEV) return map;
  try {
    const out = execFileSync(
      'git',
      ['-c', 'core.quotepath=false', 'log', '--format=%x01%cI', '--name-only', '--', '.'],
      { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] },
    );
    let date = null;
    for (const line of out.split('\n')) {
      if (line.startsWith('\x01')) { date = line.slice(1, 11); continue; }
      const f = line.trim();
      if (f && date && !map.has(f)) map.set(f, date);
    }
  } catch {
    /* not a git checkout, or git unavailable: mtime fallback below */
  }
  return map;
}

function buildSitemap(pages, ctx) {
  const { order, pageIndex } = ctx;
  const dates = gitLastModified();
  const lastmod = (abs) => {
    const rel = relative(ROOT, abs).split(sep).join('/');
    return dates.get(rel) || statSync(abs).mtime.toISOString().slice(0, 10);
  };

  const entries = pages
    .filter((p) => !isSitemapExcluded(p.canon) && !p.noindex)
    .sort((a, b) => (a.canon === b.canon
      ? order.indexOf(a.locale) - order.indexOf(b.locale)
      : a.canon.localeCompare(b.canon)));

  const urls = entries.map((p) => {
    const { changefreq, priority } = sitemapMeta(p.canon);
    const available = pageIndex.get(p.canon);
    const alternates = order
      .filter((l) => available.has(l))
      .map((l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${escapeXml(SITE_ORIGIN + localizedPath(p.canon, l))}" />`);
    // A single-language page needs no alternates; hreflang only makes sense in a set.
    if (alternates.length > 1) {
      const xDefault = available.has(DEFAULT_LOCALE) ? DEFAULT_LOCALE : order.find((l) => available.has(l));
      alternates.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(SITE_ORIGIN + localizedPath(p.canon, xDefault))}" />`);
    }
    return [
      '  <url>',
      `    <loc>${escapeXml(SITE_ORIGIN + localizedPath(p.canon, p.locale))}</loc>`,
      `    <lastmod>${lastmod(p.abs)}</lastmod>`,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      ...(alternates.length > 1 ? alternates : []),
      '  </url>',
    ].join('\n');
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by build.mjs from the pages in this build. Do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n');
}

/* ------------------------------------------------------------------- build */

export async function build({ dev = false } = {}) {
  DEV = dev;
  const t0 = Date.now();
  rmSync(DIST, { recursive: true, force: true });
  mkdirSync(DIST, { recursive: true });

  const files = { html: [], css: [], js: [], other: [] };
  walk(ROOT, files);

  const moduleSet = computeModuleSet(files.html, files.js);
  const manifest = new Map(); // original web path -> hashed web path

  // --- i18n: which pages exist in which languages --------------------------
  const locales = loadLocales();
  const order = localeOrder(locales);
  const pages = files.html.map((abs) => {
    const src = readFileSync(abs, 'utf8');
    return {
      abs,
      ...pageIdentity(abs, locales),
      usesPartials: /<!--\s*@include\s/.test(src),
      noindex: /<meta[^>]+name=["']robots["'][^>]+content=["'][^"']*noindex/i.test(src),
    };
  });
  const pageIndex = new Map(); // canon -> Set(locale)
  for (const p of pages) {
    if (!pageIndex.has(p.canon)) pageIndex.set(p.canon, new Set());
    pageIndex.get(p.canon).add(p.locale);
  }
  const i18nCtx = { locales, order, pageIndex };

  // --- CSS ---------------------------------------------------------------
  for (const cssPath of files.css) {
    const src = readFileSync(cssPath);
    let out = src;
    if (!DEV) {
      try {
        out = lightningTransform({ filename: cssPath, code: src, minify: true, errorRecovery: true }).code;
      } catch (err) {
        console.warn(`  ! CSS minify failed for ${toWebPath(cssPath)} — shipping raw (${err.message})`);
        out = src;
      }
    }
    const webOrig = toWebPath(cssPath);
    const webOut = DEV ? webOrig : hashedWebPath(webOrig, out);
    writeDist(webOut, out);
    if (!DEV) manifest.set(webOrig, webOut);
  }

  // --- JS ----------------------------------------------------------------
  for (const jsPath of files.js) {
    const isModule = moduleSet.has(jsPath);
    let out = readFileSync(jsPath, 'utf8');
    if (!DEV) {
      try {
        out = (await esbuildTransform(out, {
          loader: 'js', minify: true, target: JS_TARGET, legalComments: 'none',
        })).code;
      } catch (err) {
        console.warn(`  ! JS minify failed for ${toWebPath(jsPath)} — shipping raw (${err.message})`);
        out = readFileSync(jsPath, 'utf8');
      }
    }
    const webOrig = toWebPath(jsPath);
    // Modules keep their name so import specifiers resolve; classic scripts get hashed.
    const webOut = (DEV || isModule) ? webOrig : hashedWebPath(webOrig, out);
    writeDist(webOut, out);
    if (!DEV && !isModule) manifest.set(webOrig, webOut);
  }

  // --- passthrough assets ------------------------------------------------
  for (const f of files.other) {
    const abs = join(DIST, relative(ROOT, f));
    mkdirSync(dirname(abs), { recursive: true });
    cpSync(f, abs);
  }

  // --- HTML (last: needs the asset manifest) -----------------------------
  const rewrites = [...manifest.entries()].sort((a, b) => b[0].length - a[0].length);
  for (const page of pages) {
    const htmlPath = page.abs;
    let html = resolveIncludes(readFileSync(htmlPath, 'utf8'), htmlPath);
    html = localizeHtml(html, page, { ...i18nCtx, file: toWebPath(htmlPath) });
    // Only the public site shares scripts that read window.I18N; the Domus/login app
    // shell has its own and stays untouched.
    if (page.usesPartials && /<\/head>/i.test(html)) {
      html = html.replace(/<\/head>/i, `    ${runtimeI18nTag(page, i18nCtx)}\n</head>`);
    }
    for (const [orig, hashed] of rewrites) {
      html = html.replace(new RegExp(escapeRe(orig) + `(?=["'?#\\s>])`, 'g'), hashed);
    }
    if (!DEV) {
      try {
        html = await minifyHtml(html, HTML_MIN_OPTS);
      } catch (err) {
        console.warn(`  ! HTML minify failed for ${toWebPath(htmlPath)} — shipping unminified (${err.message.split('\n')[0]})`);
      }
    }
    writeDist(toWebPath(htmlPath), html);
  }

  // --- sitemap (needs the final page list) -------------------------------
  writeDist('/sitemap.xml', buildSitemap(pages, i18nCtx));

  const ms = Date.now() - t0;
  const translated = pages.filter((p) => p.locale !== DEFAULT_LOCALE).length;
  console.log(
    `${DEV ? 'dev' : 'prod'} build: ${files.html.length} html (${translated} translated, ` +
    `${order.length} locales), ${files.css.length} css, ` +
    `${files.js.length} js (${moduleSet.size} modules kept), ${files.other.length} assets ` +
    `→ dist/ in ${ms}ms`,
  );
  return { files, moduleSet, manifest, pages };
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  build({ dev: process.argv.includes('--dev') }).catch((err) => {
    console.error('\nBuild failed:', err);
    process.exit(1);
  });
}
